version: '3.8'

services:

  ec-rabbitmq:
    image: rabbitmq:3.11-management
    hostname: ec-rabbitmq
    container_name: ec-rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"

  ec-postgres:
    image: postgres:14.1
    container_name: ec-postgres
    hostname: ec-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: englishcompanion
      POSTGRES_PASSWORD: englishcompanion
      POSTGRES_DB: englishcompanion